version: '2'
services:
    pgmaster2:
#        image: paunin/postgresql-cluster-pgsql
        build:
            context: .
            dockerfile: Pgsql.Dockerfile
        environment:

            INITIAL_NODE_TYPE: master
            NODE_ID: 1
            NODE_NAME: node1
            CLUSTER_NODE_NETWORK_NAME: pgmaster2

            POSTGRES_PASSWORD: monkey_pass
            POSTGRES_USER: monkey_user
            POSTGRES_DB: monkey_db

            CONFIGS: "listen_addresses:'*'"
        ports:
            - 5439:5432
        networks:
            cluster:
                aliases:
                    - pgmaster2